// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Hidden from "./Hidden.mjs";
import * as Counter from "./Counter.mjs";
import * as Greeting from "./Greeting.mjs";
import * as RescriptReactRouter from "../node_modules/@rescript/react/src/RescriptReactRouter.mjs";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return React.createElement("div", undefined, "Home page", React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement("a", {
                            href: "/hello"
                          }, "Greeting")), React.createElement("li", undefined, React.createElement("a", {
                            href: "/button"
                          }, "Counter")), React.createElement("li", undefined, React.createElement("a", {
                            href: "/things/all"
                          }, "Everything")), React.createElement("li", undefined, React.createElement("a", {
                            href: "/things/blue"
                          }, "Blue")), React.createElement("li", undefined, React.createElement("a", {
                            href: "/things/red"
                          }, "Red")), React.createElement("li", undefined, React.createElement("a", {
                            href: "/hidden"
                          }, "Hide and Show"))));
  }
  switch (match.hd) {
    case "button" :
        if (!match.tl) {
          return React.createElement(Counter.make, {});
        }
        break;
    case "hello" :
        if (!match.tl) {
          return React.createElement(Greeting.make, {});
        }
        break;
    case "hidden" :
        if (!match.tl) {
          return React.createElement(Hidden.make, {});
        }
        break;
    case "things" :
        var match$1 = match.tl;
        if (match$1) {
          var title = match$1.hd;
          if (title === "all") {
            if (!match$1.tl) {
              return React.createElement("div", undefined, "View Everything");
            }
            
          } else if (!match$1.tl) {
            return React.createElement("div", undefined, "View " + title + " ones");
          }
          
        }
        break;
    default:
      
  }
  return React.createElement("div", undefined, "404");
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
