// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/rescript/lib/es6/curry.js";
import * as React from "react";

function Hidden(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setShow1 = match[1];
  var show1 = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setShow2 = match$1[1];
  var show2 = match$1[0];
  var match$2 = React.useState(function () {
        return false;
      });
  var setShow3 = match$2[1];
  var show3 = match$2[0];
  React.useEffect((function () {
          console.log("show1=" + (
                show1 ? "true" : "false"
              ) + " show2=" + (
                show2 ? "true" : "false"
              ) + " show3=" + (
                show3 ? "true" : "false"
              ));
          
        }), [
        show1,
        show2,
        show3
      ]);
  var onClick1 = function (_evt) {
    Curry._1(setShow1, (function (prev) {
            return !prev;
          }));
    Curry._1(setShow2, (function (_prev) {
            return false;
          }));
    return Curry._1(setShow3, (function (_prev) {
                  return false;
                }));
  };
  var onClick2 = function (_evt) {
    Curry._1(setShow2, (function (prev) {
            return !prev;
          }));
    return Curry._1(setShow3, (function (_prev) {
                  return false;
                }));
  };
  var onClick3 = function (_evt) {
    return Curry._1(setShow3, (function (prev) {
                  return !prev;
                }));
  };
  return React.createElement("div", undefined, React.createElement("p", undefined, "Click the Buttons to change: show1=" + (
                  show1 ? "true" : "false"
                ) + " show2=" + (
                  show2 ? "true" : "false"
                ) + " show3=" + (
                  show3 ? "true" : "false"
                )), React.createElement("p", undefined, React.createElement("button", {
                      onClick: onClick1
                    }, "0) Click me")), show1 ? React.createElement("p", undefined, React.createElement("button", {
                        onClick: onClick2
                      }, "1) Click me")) : null, show2 ? React.createElement("p", undefined, React.createElement("button", {
                        onClick: onClick3
                      }, "2) Click me")) : null, show3 ? React.createElement("p", undefined, "3) You did it!") : null);
}

var make = Hidden;

export {
  make ,
  
}
/* react Not a pure module */
